add_newline = false
format = """\
$username\
$directory\
$git_branch\
$git_state\
$memory_usage\
$env_var\
$crystal\
$cmd_duration\
$custom\
$battery\
$time\
$character\
"""

[package]
disabled = true
